// Copyright of the Graviton Forge at the Antimatter Factory. All Rights Reserved.

// Licensed under the GNU Affero General Public License, Version 3.0.

// You may obtain a copy of the License at:
// https://www.gnu.org/licenses/lgpl-3.0.en.html

= Data Interchange Format

* Data Source File: .data
* Schema Definition Header File: .schema
* .data Files Must be Dynamically Typed
* .data Files Cannot be Statically Typed
* .data Files are Required
* .schema Files Must be Statically Typed
* .schema Files Cannot be Dynamically Typed
* .schema Files are Optional
* // This is a Comment
* # This is a Comment
* /* This is a Multi-Line Comment *\
* #* This is a Multi-Line Comment *#
* /! This is a Documentation Comment
* #! This is a Documentation Comment
* /!* This is a Multi-Line Documentation Comment *!\
* #!* This is a Multi-Line Documentation Comment *!#

== Dynamically Typed Syntax

[,shell]
----
// Data Structure Initialized Declaration
// Syntax - Name {fields};
DataStructure {
	integer_type = 1;
	float_type = 1.0;
	boolean_type = true;
	character_type = 'a';
	string_type = "string";
	array_type = [];
	map_type = [];
	structure_type = DataStructure {};
};

// Boolean Initialization
// Syntax - name = value;
// OR
// Null Syntax - name = null;
boolean_type = true;

// Character Initialization
// Syntax - name = value;
// OR
// Null Syntax - name = null;
// Encoding Dependent: ASCII, UTF-8, UTF-16, UTF-32
character_type = 'a';

// Float Initialization
// Syntax - name = value;
// OR
// Null Syntax - name = null;
float_type = 1.0;

// Integer Initialization
// Syntax - name = value;
// OR
// Null Syntax - name = null;
integer_type = 1;

// String Initialization
// Syntax - name = value;
// OR
// Null Syntax - name = null;
// Encoding Dependent: ASCII, UTF-8, UTF-16, UTF-32
string_type = "string";

// Array Initialization
// Syntax - name = [values];
// OR
// Null Syntax - name = [null];
array_type = [
	1,
	2,
	3,
	4,
	5
];

// Hash Map Initialization
// Syntax - name = [(key:value)];
// OR
// Null Syntax - name = [(null:null];
map_type = [
	(1:"string"),
	(2:"string"),
	(3:"string"),
	(4:"string"),
	(5:"string")
];
----

== Statically Typed Syntax

[,shell]
----
// Data Structure Keyword - struct

// Platform Dependent Types:
// usize - Unsigned Integer Size
// isize - Signed Integer Size
// fsize - Floating Point Integer Size

// Data Structure Declaration
// Syntax - struct Name {fields};
struct DataStructure {
	unsigned_integer_size: usize;
	unsigned_integer_8bit: uint8;
	unsigned_integer_16bit: uint16;
	unsigned_integer_32bit: uint32;
	unsigned_integer_64bit: uint64;
	unsigned_integer_128bit: uint128;
	signed_integer_size: isize;
	signed_integer_8bit: int8;
	signed_integer_16bit: int16;
	signed_integer_32bit: int32;
	signed_integer_64bit: int64;
	signed_integer_128bit: int128;
	float_size: fsize;
	float_32bit: float32;
	float_64bit: float64;
	float_128bit: float128;
	boolean_type: bool;
	character_type: char;
	string_type: str;
	array_type: Vector|uint8|;
	map_type: HashMap|uint8, str|;
	structure_type: DataStructure;
};

// Data Structure Initialized Declaration
// Syntax - struct Name {fields};
struct DataStructure {
	unsigned_integer_size: usize = 0;
	unsigned_integer_8bit: uint8 = 1;
	unsigned_integer_16bit: uint16 = 2;
	unsigned_integer_32bit: uint32 = 3;
	unsigned_integer_64bit: uint64 = 4;
	unsigned_integer_128bit: uint128 = 5;
	signed_integer_size: isize = null;
	signed_integer_8bit: int8 = -1;
	signed_integer_16bit: int16 = -2;
	signed_integer_32bit: int32 = -3;
	signed_integer_64bit: int64 = -4;
	signed_integer_128bit: int128 = -5;
	float_size: fsize = null;
	float_32bit: float32 = 1.0;
	float_64bit: float64 = 2.0;
	float_128bit: float128 = 3.0;
	boolean_type: bool = true;
	character_type: char = 'a';
	string_type: str = "string";
	array_type: Vector|uint8| = [];
	map_type: HashMap|uint8, str| = [];
	structure_type: DataStructure = {};
};

// Boolean Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
boolean_type: bool = true;

// Character Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
// Encoding Dependent: ASCII, UTF-8, UTF-16, UTF-32
character_type: char = 'a';

// Float Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
float_32bit: float32 = 1.0;

// Integer Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
unsigned_integer_8bit: uint8 = 1;

// Platform Dependent Integer Size Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
// Platform Dependent: x86, x86_64, AARCH32, AARCH64, RISC32, RISC64
signed_integer_size: isize = -1;

// String Initialization
// Syntax - name: type = value;
// OR
// Null Syntax - name: type = null;
// Encoding Dependent: ASCII, UTF-8, UTF-16, UTF-32
string_type: str = "string";

// Array Initialization
// Syntax - name: Vector|type| = [values];
// OR
// Null Syntax - name: Vector|type| = [null];
array_type: Vector|uint8| = [
	1,
	2,
	3,
	4,
	5
];

// Hash Map Initialization
// Syntax - name: type|type, type| = [(key:value)];
// OR
// Null Syntax - name: type|type, type| = [(null:null)];
map_type: HashMap|uint8, str| = [
	(1:"string"),
	(2:"string"),
	(3:"string"),
	(4:"string"),
	(5:"string")
];
----

